global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'golang-ddd-app'
    static_configs:
      - targets: ['app:9090']
        labels:
          service: 'api'
          environment: 'development'
